title: Wynlla Zhao
author: wy-go
email: wanyugogo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Wynlla Zhao from School of Software of Shandong University.

# social links
twitter_username: Wynlla # DO NOT include the @ character, or else the build will fail!
github_username:  wy-go # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
